# Generated by Django 3.1.4 on 2020-12-20 11:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_ID', models.AutoField(primary_key=True, serialize=False)),
                ('training_date', models.DateField(default=datetime.date.today)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training_location')),
                ('training_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.training_type')),
            ],
            options={
                'ordering': ('-training_ID',),
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reps', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)])),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.exercise_name')),
                ('training_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.training')),
            ],
        ),
    ]
