# Generated by Django 3.1.4 on 2020-12-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_exercise_training'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='Reps',
            new_name='reps',
        ),
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='training.training_location'),
        ),
    ]
