# Generated by Django 3.1.4 on 2020-12-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20201220_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='user_name',
            field=models.CharField(default='admin', max_length=30),
            preserve_default=False,
        ),
    ]
