# Generated by Django 3.1.4 on 2020-12-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_training_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='user_name',
            field=models.CharField(default='admin', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise_name',
            name='user_name',
            field=models.CharField(default='admin', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training_location',
            name='user_name',
            field=models.CharField(default='admin', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training_type',
            name='user_name',
            field=models.CharField(default='admin', max_length=30),
            preserve_default=False,
        ),
    ]
