# Generated by Django 3.1.4 on 2021-01-05 13:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20201230_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_time',
            field=models.TimeField(default=datetime.time(14, 26, 47, 723661)),
        ),
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='training.training_location'),
        ),
    ]
