# Generated by Django 3.1.4 on 2021-01-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20210105_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
