# Generated by Django 3.1.4 on 2021-02-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20210106_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_time',
            field=models.TimeField(blank=True, default='14:45', null=True),
        ),
    ]
